# We MUST have a separate pipeline otherwise the artifacts are stale!
# this is why we use an include file instead of a single file!

stages:
  - deploy

my.remarkbox.com:
  stage: deploy
  tags: ["my.remarkbox.com"]
  needs:
    - build
  script:
    # deploy build via salt-call out to the salt-master for a highstate.
    - sudo /opt/salt-call-state-highstate.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
