stages:
  - test
  - build
  - deploy
  - pypi-twine

test:
  stage: test
  tags: ["build"]
  except:
    - tags
  script: make test
  artifacts:
    paths:
      - env.vanilla
    expire_in: 1 hour

build:
  stage: build
  tags: ["build"]
  except:
    - tags
  script:
    - ls -hal
    - mv env.vanilla env
    - make install-from-source-prod
    # Copy static assets to env/static
    - cp -pr remarkbox/static env/static
    # Copy static assets to env/static for westworld theme.
    - cp -pr env/lib/python*/site-packages/remarkbox_westworld/static/* env/static
    # Copy static assets to env/static for meta theme.
    - cp -pr env/lib/python*/site-packages/remarkbox_theme_meta/static/* env/static
    # Make tarball of the static files.
    - cp -pr env/static static
    - tar -zcf static.tar.gz static
    # Clone the virtualenv with virtualenv-clone into the desired location.
    - virtualenv-clone env /opt/remarkbox/env
    # Create a tarball of the virtualenv.
    - tar -zcf env.tar.gz -C /opt/remarkbox .
    # Create a SHA512 hash of env.tar.gz.
    - sha512sum env.tar.gz >> env.tar.gz.hash
    # Create commit-hash.txt to track this build's git commit hash.
    - echo $CI_COMMIT_SHA >> commit-hash.txt
    # Clean up the directory outside of the gitlab-runner filesystem.
    - rm -rf /opt/remarkbox/env
  artifacts:
    paths:
      - env.tar.gz
      - env.tar.gz.hash
      - static.tar.gz
      - commit-hash.txt
    expire_in: 1 month

deploy:
  stage: deploy
  needs: [build]
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main"'
      when: on_success
  trigger:
    include: .gitlab-ci.deploy.yml


pypi-twine:
  stage: pypi-twine
  tags:
    - build
  only:
    - tags
  script:
    - pip install --upgrade pip
    - pip install twine
    - python3 setup.py sdist bdist_wheel
    - twine upload dist/*
