def includeme(config):
    config.add_route("api-version", "/api/v1/version")
    config.add_route("api-threads-list", "/api/v1/threads")
    config.add_route("api-threads-search", "/api/v1/threads/search")
    config.add_route("api-thread-detail", "/api/v1/threads/{node_id}")
    config.add_route("api-thread-replies", "/api/v1/threads/{node_id}/replies")
    config.add_route("api-node-detail", "/api/v1/nodes/{node_id}")
    config.add_route("api-auth-login", "/api/v1/auth/login")
    config.add_route("api-auth-verify", "/api/v1/auth/verify")
    config.add_route("api-user-profile", "/api/v1/user/profile")
    config.add_route("api-client-python", "/api/v1/clients/python")
    config.add_route("api-client-c", "/api/v1/clients/c")
    config.add_route("api-webmention", "/api/v1/webmention")
    config.add_route("api-admin-namespaces", "/api/v1/admin/namespaces")
    config.add_route("api-admin-recent-nodes", "/api/v1/admin/recent-nodes")
    config.scan("remarkbox.api.views")
